image: openjdk:11-jdk

stages:
  - compile
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle


cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

compile:
  stage: compile
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - echo "Running the sigmotoa test..."
    - ./gradlew test --info > test-results.xml

  after_script:
    - destiny = $GITLAB_USER_EMAIL
    - subject = "Result test"
    - msg = "Attached the results"
    - attached=test-results.xml
    - mail=$(echo -e "Subject: $subject\n\n $msg")
    - if [[ -f "$attached"" ]]; then
      mail=$(echo -e "Subject: $subject\nContent-Type: text/plain; charset=utf-8\nContent-Disposition: attachment; filename=$(basename $attached)\n\n $msg" ; uuencode --base64 $attached $(basename $attached))
      fi
    - echo "$mail" | ssmtp $destiny