image: openjdk:11-jdk



stages:
  - compile
  - test

before_script:
  - apt-get update && apt-get install -y sudo
  - export GRADLE_USER_HOME=`pwd`/.gradle


cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

compile:
  stage: compile
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - echo "Running the sigmotoa test..."
    - ./gradlew test --info > test-results.xml

  after_script:
    - whoami
    - chmod +x ./src/mail.sh
    - ./src/mail.sh