image: openjdk:11-jdk

stages:
  - compile
  - test
  - send_email

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

compile:
  stage: compile
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - echo "Running the sigmotoa test..."
    - ./gradlew test --info
    - pytest --junit-xml=test-results.xml

send_email:
  stage: send_email
  script:
    - pip3 install python-gitlab
    - python3 send_mail.py $GITLAB_USER_EMAIL $GITLAB_USER_NAME "Resultado Pruebas" test-results.xml